name: "Build"

on:
  workflow_call: 

jobs:
  dist-storybook:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            dist/
          retention-days: 14
