name: "ViTest"

on:
  workflow_call: 

jobs:
  vitest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: "22.x"

      - name: Unit Tests
        run: yarn test

      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          retention-days: 14